version: '3.7'
services:
    barter_db:
        restart: 'always'
        image: mysql:5.7
        container_name: barter_db
        volumes:
            - ${PWD}/data/:/var/lib/mysql
        environment:
            #to connect : 
            #mysql --host=127.0.0.1 --port=8088 -uadmin -pdzalekaxDf0JRN9VTPLI9JyvimB
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # injected from .env
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        ports:
            - '${MYSQL_PORT}:3306'
        expose:
            - '3306'
        healthcheck:
            test: "mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""
            timeout: 10s
            retries: 10
