PREFIX barp: <https://www.barter.ie/database/predicates#>
PREFIX bard: <https://www.barter.ie/database/data#>

# find all "open" jobs in the worker's camp
SELECT ?jobID ?jobTitle ?jobDate
WHERE {
    ?job barp:id ?jobID ;
         barp:title ?jobTitle ;
         barp:datePosted ?jobDate ;
         barp:postedBy ?client ;
         barp:status "open" .
    bard:user199 barp:inCamp ?camp .
    ?client barp:inCamp ?camp .
}
