# Generated by Django 3.1.6 on 2021-03-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20210323_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('business_name', models.CharField(max_length=128, null=True)),
                ('working_days', models.CharField(max_length=128, null=True)),
                ('work_tags', models.CharField(max_length=256, null=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('contact', models.CharField(max_length=128, null=True)),
                ('start_time', models.IntegerField(null=True)),
                ('end_time', models.IntegerField(null=True)),
            ],
        ),
    ]
