PREFIX barp: <https://www.barter.ie/database/predicates#>
PREFIX bard: <https://www.barter.ie/database/data#>
PREFIX barc: <https://www.barter.ie/database/classes#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# insert a new worker into the DB
INSERT DATA {
    bard:user7556 a barc:Worker ;
                  barp:id 7556 ;
                  barp:skillTag "electrician" ;
                  barp:name "Pedro Castillo" ;
                  barp:username "pcastillo" ;
                  barp:password "password555" ;
                  barp:inCamp bard:kakuma ;
                  barp:primaryLanguage "Arabic" ;
                  barp:location bard:loc7556 .
    bard:loc7556  a barc:Location ;
                  barp:latitude 3.722455;
				  barp:longitude 34.862811 .
}
